kernel:
  image: "mobylinux/kernel:4.9.x"
  cmdline: "console=ttyS0 page_poison=1"
init:
  - mobylinux/init:61a72fa20b9b9be269fe6b2b6360031f2cb897a7 # base init + strace + git
  - mobylinux/runc:b0fb122e10dbb7e4e45115177a61a3f8d68c19a9
  - mobylinux/containerd:18eaf72f3f4f9a9f29ca1951f66df701f873060b
  - mobylinux/ca-certificates:eabc5a6e59f05aa91529d80e9a595b85b046f935
onboot:
  - name: sysctl
    image: "linuxkit/sysctl:3aa6bc663c2849ef239be7d941d3eaf3e6fcc018"
services:
  - name: rngd
    image: mobylinux/rngd:3dad6dd43270fa632ac031e99d1947f20b22eec9
  - name: dhcp-client
    image: mobylinux/dhcp-client:62aeb8659143df9bd47308e5da9be561d0d0383c
    net: host
    capabilities:
     - CAP_NET_ADMIN # to bring eth0 up
     - CAP_NET_RAW   # to read /dev/eth0
     - CAP_SYS_ADMIN # for runc (unshare)
     - CAP_SETGID    # for runc (setns)
    mounts: # for runc
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /var/run/dhcp-client:/data
     - /usr/bin/runc:/usr/bin/runc # for runc
     - /run/runc:/run/runc         # for runc
     - /sbin:/sbin   # for ifconfig
     - /bin:/bin     # for ifconfig
     - /lib:/lib     # for ifconfig
files:
  - path: /var/run/dhcp-client/README
    contents: 'data for dhcp-client'
